# Generated by Django 3.2 on 2024-11-12 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuestomRols',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50)),
                ('Departement', models.CharField(max_length=100)),
                ('addressDepartement', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('dateEdited', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=13, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('dateBorn', models.DateField()),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('dateEdited', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersPassword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('dateEdited', models.DateField(auto_now=True)),
                ('ForeignKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgres.customuser')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='cuestomrols',
            name='ForeignKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgres.customuser'),
        ),
    ]
